### GET all users
GET http://localhost:8080/usuarios/all

### Update user 2
GET http://localhost:8080/usuarios/update/2?username=Aninha

### Update user 5
GET http://localhost:8080/usuarios/update/5?username=Aninha